import type { ParamedicalProfessionPack } from './types';

export const DIETITIAN_PACK: ParamedicalProfessionPack = {
  profession: 'dietitian',
  label: 'Diététicien',
  clinicalHeaderTitle: 'Dossier de suivi nutritionnel',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Consultation',
    appointmentPlural: 'Consultations',
    serviceSingular: 'Consultation diététique',
    servicePlural: 'Consultations diététiques',
    assessmentLabel: 'Bilan nutritionnel initial',
    followUpLabel: 'Consultation de suivi diététique',
    clinicalRecordHeading: 'Dossier diététique et nutritionnel',
  },
  appointmentTypePresets: [
    {
      id: 'diet.initial_consultation',
      name: 'Première consultation diététique',
      description: 'Bilan nutritionnel approfondi, enquête alimentaire, analyse des habitudes et objectifs.',
      durationMinutes: 60,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
    {
      id: 'diet.follow_up',
      name: 'Consultation de suivi diététique',
      description: 'Suivi des ajustements alimentaires, analyse des ressentis et ajustement des objectifs.',
      durationMinutes: 30,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'diet.initial_assessment_form',
      name: 'Bilan nutritionnel initial',
      kind: 'assessment',
      description: 'Trame d’évaluation nutritionnelle : habitudes alimentaires, rythme de vie et objectifs partagés.',
      schema: {
        fields: [
          {
            id: 'motif_consultation',
            label: 'Motif de consultation diététique',
            type: 'textarea',
            required: true,
            placeholder: 'Rééquilibrage, diabète, dyslipidémie, intolérances, perte/prise de poids...',
          },
          {
            id: 'habitudes_alimentaires_declarees',
            label: 'Habitudes et rythme alimentaire déclarés',
            type: 'textarea',
            required: false,
            placeholder: 'Nombre de repas, collations, hydratation, grignotages, horaires...',
          },
          {
            id: 'activite_physique_declaree',
            label: 'Activité physique et mode de vie',
            type: 'textarea',
            required: false,
            placeholder: 'Sédentarité, activité sportive hebdomadaire, déplacements à pied...',
          },
          {
            id: 'contraintes_preferences',
            label: 'Contraintes, allergies et préférences alimentaires',
            type: 'textarea',
            required: false,
            placeholder: 'Aversions, régimes spécifiques (végétarien...), allergies, budget...',
          },
          {
            id: 'objectifs_nutritionnels',
            label: 'Objectifs nutritionnels co-définis',
            type: 'textarea',
            required: false,
            placeholder: 'Objectifs réalistes, étapes d’action prioritaires...',
          },
          {
            id: 'plan_alimentaire_recommande',
            label: 'Recommandations et axes de rééquilibrage',
            type: 'textarea',
            required: false,
            placeholder: 'Conseils pratiques, suggestions de repas équilibrés...',
          },
        ],
      },
    },
    {
      id: 'diet.nutrition_follow_up_form',
      name: 'Suivi nutritionnel',
      kind: 'follow_up',
      description: 'Trame de suivi des habitudes et ressentis nutritionnels.',
      schema: {
        fields: [
          {
            id: 'evolution_ressentie',
            label: 'Évolution et ressenti depuis la dernière consultation',
            type: 'textarea',
            required: true,
            placeholder: 'Niveau d’énergie, confort digestif, relation à l’alimentation...',
          },
          {
            id: 'difficultes_rencontrees',
            label: 'Difficultés ou écarts rencontrés',
            type: 'textarea',
            required: false,
            placeholder: 'Moments plus compliqués (sorties, stress, manque de temps)...',
          },
          {
            id: 'adhesion_objectifs',
            label: 'Adhésion aux objectifs fixés (1-5)',
            type: 'scale',
            min: 1,
            max: 5,
            step: 1,
            required: false,
          },
          {
            id: 'ajustements_conseils',
            label: 'Ajustements et nouveaux objectifs',
            type: 'textarea',
            required: false,
            placeholder: 'Adaptation des portions, nouvelles recettes, encouragement...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'weight',
      label: 'Poids corporel',
      valueType: 'numeric',
      unit: 'kg',
      description: 'Poids mesuré en consultation en kilogrammes.',
    },
    {
      code: 'height',
      label: 'Taille',
      valueType: 'numeric',
      unit: 'cm',
      description: 'Taille en centimètres.',
    },
    {
      code: 'bmi',
      label: 'Indice de masse corporelle (IMC)',
      valueType: 'numeric',
      unit: 'kg/m²',
      description: 'Indice de masse corporelle (rapport poids/taille²).',
    },
    {
      code: 'waist_circumference',
      label: 'Tour de taille',
      valueType: 'numeric',
      unit: 'cm',
      description: 'Circonférence abdominale mesurée en centimètres.',
    },
  ],
};
