import type { ParamedicalProfessionPack } from './types';

export const OCCUPATIONAL_THERAPIST_PACK: ParamedicalProfessionPack = {
  profession: 'occupational_therapist',
  label: 'Ergothérapeute',
  clinicalHeaderTitle: 'Dossier de suivi en ergothérapie',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Séance',
    appointmentPlural: 'Séances',
    serviceSingular: 'Séance d’ergothérapie',
    servicePlural: 'Séances d’ergothérapie',
    assessmentLabel: 'Évaluation initiale en ergothérapie',
    followUpLabel: 'Séance de réadaptation',
    clinicalRecordHeading: 'Dossier d’ergothérapie',
  },
  appointmentTypePresets: [
    {
      id: 'ot.initial_assessment',
      name: 'Évaluation initiale en ergothérapie',
      description: 'Évaluation globale de l’autonomie dans les actes de la vie quotidienne et de l’environnement.',
      durationMinutes: 60,
      bufferBeforeMinutes: 10,
      bufferAfterMinutes: 10,
      slotStepMinutes: 15,
    },
    {
      id: 'ot.follow_up',
      name: 'Séance de réadaptation en ergothérapie',
      description: 'Entraînement aux activités, mise en situation écologique et adaptation des aides techniques.',
      durationMinutes: 45,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'ot.initial_assessment_form',
      name: 'Évaluation initiale des activités quotidiennes',
      kind: 'assessment',
      description: 'Trame d’évaluation initiale : autonomie quotidienne, environnement et aménagements préconisés.',
      schema: {
        fields: [
          {
            id: 'motif_demande',
            label: 'Motif de l’intervention en ergothérapie',
            type: 'textarea',
            required: true,
            placeholder: 'Maintien à domicile, retour au travail, autonomie post-AVC/traumatisme...',
          },
          {
            id: 'activites_vie_quotidienne',
            label: 'Activités de la vie quotidienne (AVQ) impactées',
            type: 'textarea',
            required: false,
            placeholder: 'Toilette, habillage, préparation des repas, déplacements, conduite...',
          },
          {
            id: 'difficultes_identifiees',
            label: 'Difficultés motrices, cognitives ou sensorielles identifiées',
            type: 'textarea',
            required: false,
            placeholder: 'Préhensions, fatigabilité, repérage spatial, équilibre...',
          },
          {
            id: 'environnement_de_vie',
            label: 'Environnement de vie et obstacles architecturaux',
            type: 'textarea',
            required: false,
            placeholder: 'Escaliers, accès douche, seuils de porte, disposition du mobilier...',
          },
          {
            id: 'objectifs_ergotherapie',
            label: 'Objectifs d’indépendance partagés',
            type: 'textarea',
            required: false,
            placeholder: 'Sécurisation des transferts, compensation technique, préconisations...',
          },
          {
            id: 'adaptations_preconisees',
            label: 'Aménagements ou aides techniques préconisés',
            type: 'textarea',
            required: false,
            placeholder: 'Barres d’appui, siège de bain, aménagement de poste, aides aux repas...',
          },
        ],
      },
    },
    {
      id: 'ot.functional_follow_up_form',
      name: 'Suivi fonctionnel en ergothérapie',
      kind: 'follow_up',
      description: 'Trame de suivi des mises en situation et adaptations.',
      schema: {
        fields: [
          {
            id: 'activites_travaillees',
            label: 'Activités travaillées lors de la séance',
            type: 'textarea',
            required: true,
            placeholder: 'Mise en situation écologique, utilisation d’aides techniques...',
          },
          {
            id: 'autonomie_observee',
            label: 'Niveau d’autonomie observé (1-5)',
            type: 'scale',
            min: 1,
            max: 5,
            step: 1,
            required: false,
          },
          {
            id: 'progression_objectifs',
            label: 'Progression par rapport aux objectifs fixés',
            type: 'textarea',
            required: false,
            placeholder: 'Fluidité du geste, réduction des compensations néfastes...',
          },
          {
            id: 'ajustements_preconisations',
            label: 'Ajustements des aides ou des consignes',
            type: 'textarea',
            required: false,
            placeholder: 'Réglages d’équipements, conseils pour les aidants...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'functional_independence_score',
      label: 'Indice indicatif d’indépendance fonctionnelle',
      valueType: 'numeric',
      unit: '/100',
      description: 'Indice global indicatif d’autonomie dans les AVQ.',
    },
    {
      code: 'goal_progress',
      label: 'Progression des objectifs d’autonomie',
      valueType: 'numeric',
      unit: '%',
      description: 'Pourcentage indicatif de réalisation des objectifs cibles.',
    },
    {
      code: 'autonomy_score',
      label: 'Niveau d’autonomie observé',
      valueType: 'numeric',
      unit: '/5',
      description: 'Niveau d’indépendance sur l’activité évaluée.',
    },
  ],
};
