import type { ParamedicalProfessionPack } from './types';

export const OSTEOPATH_PACK: ParamedicalProfessionPack = {
  profession: 'osteopath',
  label: 'Ostéopathe',
  clinicalHeaderTitle: 'Dossier de suivi ostéopathique',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Consultation',
    appointmentPlural: 'Consultations',
    serviceSingular: 'Consultation d’ostéopathie',
    servicePlural: 'Consultations d’ostéopathie',
    assessmentLabel: 'Première consultation ostéopathique',
    followUpLabel: 'Consultation de suivi',
    clinicalRecordHeading: 'Dossier ostéopathique',
  },
  appointmentTypePresets: [
    {
      id: 'osteo.initial_consultation',
      name: 'Première consultation ostéopathique',
      description: 'Bilan ostéopathique complet, anamnèse, tests d’exclusion et premier traitement.',
      durationMinutes: 60,
      bufferBeforeMinutes: 10,
      bufferAfterMinutes: 10,
      slotStepMinutes: 15,
    },
    {
      id: 'osteo.follow_up',
      name: 'Consultation de suivi ostéopathique',
      description: 'Réévaluation posturale et tissulaire, ajustement des dysfonctions résiduelles.',
      durationMinutes: 45,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'osteo.initial_consultation_form',
      name: 'Première consultation ostéopathique',
      kind: 'assessment',
      description: 'Trame d’anamnèse ostéopathique : motif, antécédents, zone douloureuse et observations tissulaires.',
      schema: {
        fields: [
          {
            id: 'motif_consultation',
            label: 'Motif principal de consultation',
            type: 'textarea',
            required: true,
            placeholder: 'Gêne principale, localisation...',
          },
          {
            id: 'antecedents_traumatismes',
            label: 'Antécédents médicaux et chirurgicaux déclarés',
            type: 'textarea',
            required: false,
            placeholder: 'Fractures, entorses, chirurgies, antécédents marquants...',
          },
          {
            id: 'zone_douloureuse_principale',
            label: 'Zone douloureuse ou de restriction principale',
            type: 'text',
            required: false,
            placeholder: 'Rachis cervical, lombaire, bassin, viscéral...',
          },
          {
            id: 'douleur_declaree',
            label: 'Intensité douloureuse (EVA 0-10)',
            type: 'scale',
            min: 0,
            max: 10,
            step: 1,
            required: true,
          },
          {
            id: 'observations_posturales',
            label: 'Observations posturales et tissulaires',
            type: 'textarea',
            required: false,
            placeholder: 'Asymétries, restrictions de mobilité tissulaire constatées...',
          },
          {
            id: 'axes_traitement',
            label: 'Axes de traitement ostéopathique',
            type: 'textarea',
            required: false,
            placeholder: 'Techniques manuelles douces, conseils et suivi...',
          },
        ],
      },
    },
    {
      id: 'osteo.follow_up_form',
      name: 'Suivi de consultation ostéopathique',
      kind: 'follow_up',
      description: 'Trame de réévaluation ostéopathique et évolution posturale.',
      schema: {
        fields: [
          {
            id: 'evolution_ressentie',
            label: 'Évolution ressentie depuis la séance précédente',
            type: 'textarea',
            required: true,
            placeholder: 'Amélioration, réactions secondaires éventuelles...',
          },
          {
            id: 'douleur_actuelle',
            label: 'Intensité de la gêne actuelle (EVA 0-10)',
            type: 'scale',
            min: 0,
            max: 10,
            step: 1,
            required: false,
          },
          {
            id: 'zones_traitees',
            label: 'Zones travaillées lors de la consultation',
            type: 'textarea',
            required: false,
            placeholder: 'Régions traitées, techniques utilisées...',
          },
          {
            id: 'conseils_hygiene_posturale',
            label: 'Conseils posturaux et recommandations',
            type: 'textarea',
            required: false,
            placeholder: 'Conseils ergonomiques, étirements d’entretien...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'pain_score',
      label: 'Échelle de la douleur (EVA)',
      valueType: 'numeric',
      unit: '/10',
      description: 'Intensité de la douleur ressentie.',
    },
    {
      code: 'mobility_score',
      label: 'Indice d’aisance de mobilité',
      valueType: 'numeric',
      unit: '/10',
      description: 'Estimation de l’aisance globale de mouvement.',
    },
    {
      code: 'posture_observation',
      label: 'Observation posturale',
      valueType: 'text',
      unit: null,
      description: 'Note qualitative de l’équilibre postural.',
    },
  ],
};
