import type { ParamedicalProfessionPack } from './types';

export const PHYSIOTHERAPIST_PACK: ParamedicalProfessionPack = {
  profession: 'physiotherapist',
  label: 'Masseur-Kinésithérapeute',
  shortLabel: 'Kinésithérapeute',
  clinicalHeaderTitle: 'Dossier de suivi kinésithérapique',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Séance',
    appointmentPlural: 'Séances',
    serviceSingular: 'Séance de kinésithérapie',
    servicePlural: 'Séances de kinésithérapie',
    assessmentLabel: 'Bilan initial de kinésithérapie',
    followUpLabel: 'Séance de suivi',
    clinicalRecordHeading: 'Dossier kinésithérapique',
  },
  appointmentTypePresets: [
    {
      id: 'physio.initial_assessment',
      name: 'Bilan initial de kinésithérapie',
      description: 'Évaluation clinique initiale, anamnèse et élaboration du projet thérapeutique.',
      durationMinutes: 45,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
    {
      id: 'physio.follow_up',
      name: 'Séance de suivi de kinésithérapie',
      description: 'Séance de rééducation et de réadaptation motrice et fonctionnelle.',
      durationMinutes: 30,
      bufferBeforeMinutes: 0,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'physio.initial_assessment_form',
      name: 'Bilan initial kinésithérapique',
      kind: 'assessment',
      description: 'Trame d’évaluation initiale : motif, douleur déclarée, mobilité et objectifs de rééducation.',
      schema: {
        fields: [
          {
            id: 'motif_prise_en_charge',
            label: 'Motif de prise en charge',
            type: 'textarea',
            required: true,
            placeholder: 'Motif d’orientation, diagnostic médical initial...',
          },
          {
            id: 'contexte_apparition',
            label: 'Contexte et antécédents pertinents',
            type: 'textarea',
            required: false,
            placeholder: 'Circonstances d’apparition, antécédents traumatiques ou chirurgicaux...',
          },
          {
            id: 'douleur_declaree',
            label: 'Douleur déclarée (EVA 0-10)',
            type: 'scale',
            min: 0,
            max: 10,
            step: 1,
            required: true,
          },
          {
            id: 'limitations_fonctionnelles',
            label: 'Limitations fonctionnelles observées',
            type: 'textarea',
            required: false,
            placeholder: 'Impact sur la marche, les gestes de la vie quotidienne ou professionnelle...',
          },
          {
            id: 'mobilite_observee',
            label: 'Mobilité et amplitudes observées',
            type: 'textarea',
            required: false,
            placeholder: 'Amplitudes articulaires, testing musculaire ou palpatoire...',
          },
          {
            id: 'objectifs_patient',
            label: 'Objectifs partagés avec le patient',
            type: 'textarea',
            required: false,
            placeholder: 'Attentes du patient, autonomie recherchée...',
          },
          {
            id: 'plan_suivi_libre',
            label: 'Plan de suivi kinésithérapique',
            type: 'textarea',
            required: false,
            placeholder: 'Axes de travail, fréquence préconisée, exercices...',
          },
        ],
      },
    },
    {
      id: 'physio.session_follow_up_form',
      name: 'Suivi de séance kinésithérapique',
      kind: 'follow_up',
      description: 'Trame de suivi régulier de rééducation motrice.',
      schema: {
        fields: [
          {
            id: 'evolution_symptomes',
            label: 'Évolution des symptômes rapportée',
            type: 'textarea',
            required: true,
            placeholder: 'Ressenti depuis la dernière séance...',
          },
          {
            id: 'douleur_seance',
            label: 'Niveau de douleur actuel (EVA 0-10)',
            type: 'scale',
            min: 0,
            max: 10,
            step: 1,
            required: false,
          },
          {
            id: 'exercices_realises',
            label: 'Exercices et techniques appliquées',
            type: 'textarea',
            required: false,
            placeholder: 'Mobilisations, renforcement, étirements...',
          },
          {
            id: 'observations_cliniques',
            label: 'Observations et adaptation du protocole',
            type: 'textarea',
            required: false,
            placeholder: 'Réponse aux exercices, tolérance à l’effort...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'pain_score',
      label: 'Échelle visuelle de la douleur (EVA)',
      valueType: 'numeric',
      unit: '/10',
      description: 'Intensité de la douleur rapportée sur l’échelle de 0 à 10.',
    },
    {
      code: 'range_of_motion',
      label: 'Amplitude articulaire',
      valueType: 'numeric',
      unit: '°',
      description: 'Mesure goniométrique en degrés.',
    },
    {
      code: 'walking_distance',
      label: 'Périmètre de marche',
      valueType: 'numeric',
      unit: 'm',
      description: 'Distance de marche sans arrêt en mètres.',
    },
    {
      code: 'functional_score',
      label: 'Score fonctionnel indicatif',
      valueType: 'numeric',
      unit: '/100',
      description: 'Indice fonctionnel estimé.',
    },
  ],
};
