import type { ParamedicalProfessionPack } from './types';

export const PODIATRIST_PACK: ParamedicalProfessionPack = {
  profession: 'podiatrist',
  label: 'Pédicure-Podologue',
  shortLabel: 'Podologue',
  clinicalHeaderTitle: 'Dossier de suivi podologique',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Séance',
    appointmentPlural: 'Séances',
    serviceSingular: 'Soin / Consultation podologique',
    servicePlural: 'Soins / Consultations podologiques',
    assessmentLabel: 'Bilan podologique et postural',
    followUpLabel: 'Soin de suivi / Contrôle',
    clinicalRecordHeading: 'Dossier podologique',
  },
  appointmentTypePresets: [
    {
      id: 'podiatrist.initial_assessment',
      name: 'Bilan podologique et postural',
      description: 'Examen clinique podologique, statique et dynamique, examen des appuis et de la marche.',
      durationMinutes: 45,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
    {
      id: 'podiatrist.care_follow_up',
      name: 'Soin de pédicurie / Suivi podologique',
      description: 'Soin instrumental dermatologique/unguéal ou vérification d’orthèses plantaires.',
      durationMinutes: 30,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'podiatrist.initial_assessment_form',
      name: 'Bilan podologique et postural initial',
      kind: 'assessment',
      description: 'Trame d’examen clinique podologique : motif, douleurs, chaussage et proposition d’appareillage.',
      schema: {
        fields: [
          {
            id: 'motif_consultation',
            label: 'Motif de consultation',
            type: 'textarea',
            required: true,
            placeholder: 'Douleurs à la marche, cors, ongles incarnés, instabilité...',
          },
          {
            id: 'localisation_douleur',
            label: 'Localisation de la gêne ou douleur',
            type: 'text',
            required: false,
            placeholder: 'Avant-pied, talon, voûte, cheville, genou...',
          },
          {
            id: 'douleur_declaree',
            label: 'Intensité de la douleur (EVA 0-10)',
            type: 'scale',
            min: 0,
            max: 10,
            step: 1,
            required: true,
          },
          {
            id: 'type_chaussage',
            label: 'Chaussage habituel et contraintes professionnelles/sportives',
            type: 'text',
            required: false,
            placeholder: 'Chaussures de sécurité, baskets running, talons, usure asymétrique...',
          },
          {
            id: 'observations_statiques_dynamiques',
            label: 'Observations en statique et dynamique',
            type: 'textarea',
            required: false,
            placeholder: 'Empreintes podométriques, axe calcanéen, déroulé du pas...',
          },
          {
            id: 'appareillage_preconise',
            label: 'Proposition de prise en charge',
            type: 'single_choice',
            required: false,
            options: [
              { value: 'semelles_thermoformees', label: 'Semelles orthopédiques thermoformées' },
              { value: 'semelles_classiques', label: 'Semelles orthopédiques classiques' },
              { value: 'orthoplastie', label: 'Orthoplastie / Petit appareillage' },
              { value: 'soin_pedicurie', label: 'Soin de pédicurie uniquement' },
              { value: 'surveillance', label: 'Surveillance / Conseils de chaussage' },
            ],
          },
          {
            id: 'plan_suivi',
            label: 'Remarques et plan de suivi',
            type: 'textarea',
            required: false,
            placeholder: 'Date préconisée de contrôle des semelles, conseils...',
          },
        ],
      },
    },
    {
      id: 'podiatrist.care_follow_up_form',
      name: 'Suivi de soin et appareillage podologique',
      kind: 'follow_up',
      description: 'Trame de contrôle de semelles ou soin de pédicurie de suivi.',
      schema: {
        fields: [
          {
            id: 'evolution_douleur',
            label: 'Évolution de la douleur ou de la gêne',
            type: 'textarea',
            required: true,
            placeholder: 'Adaptation aux semelles, port régulier...',
          },
          {
            id: 'confort_appareillage',
            label: 'Confort de l’appareillage / chaussage (1-5)',
            type: 'scale',
            min: 1,
            max: 5,
            step: 1,
            required: false,
          },
          {
            id: 'soins_realises',
            label: 'Gestes ou ajustements réalisés',
            type: 'textarea',
            required: false,
            placeholder: 'Modifications d’éléments sous semelle, fraisage, coupe...',
          },
          {
            id: 'consignes_patient',
            label: 'Consignes d’entretien et prochain contrôle',
            type: 'textarea',
            required: false,
            placeholder: 'Hydratation, séchage, date du prochain contrôle...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'pain_score',
      label: 'Échelle de la douleur (EVA)',
      valueType: 'numeric',
      unit: '/10',
      description: 'Intensité de la douleur lors des appuis ou de la marche.',
    },
    {
      code: 'mobility_score',
      label: 'Indice de mobilité / confort à la marche',
      valueType: 'numeric',
      unit: '/10',
      description: 'Estimation de la fluidité de la marche.',
    },
    {
      code: 'comfort_rating',
      label: 'Confort du chaussage / appareillage',
      valueType: 'numeric',
      unit: '/5',
      description: 'Niveau de confort rapporté par le patient.',
    },
  ],
};
