import type { ParamedicalProfessionPack } from './types';

export const PSYCHOMOTOR_THERAPIST_PACK: ParamedicalProfessionPack = {
  profession: 'psychomotor_therapist',
  label: 'Psychomotricien',
  clinicalHeaderTitle: 'Dossier de suivi psychomoteur',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Séance',
    appointmentPlural: 'Séances',
    serviceSingular: 'Séance de psychomotricité',
    servicePlural: 'Séances de psychomotricité',
    assessmentLabel: 'Bilan psychomoteur initial',
    followUpLabel: 'Séance de suivi psychomoteur',
    clinicalRecordHeading: 'Dossier psychomoteur',
  },
  appointmentTypePresets: [
    {
      id: 'psychomotor.initial_assessment',
      name: 'Bilan psychomoteur initial',
      description: 'Bilan des fonctions psychomotrices, motricité globale/fine, schéma corporel et espace-temps.',
      durationMinutes: 60,
      bufferBeforeMinutes: 10,
      bufferAfterMinutes: 10,
      slotStepMinutes: 15,
    },
    {
      id: 'psychomotor.follow_up',
      name: 'Séance de suivi psychomoteur',
      description: 'Séance de rééducation et de médiation corporelle psychomotrice.',
      durationMinutes: 45,
      bufferBeforeMinutes: 5,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'psychomotor.initial_assessment_form',
      name: 'Bilan psychomoteur initial',
      kind: 'assessment',
      description: 'Trame d’évaluation initiale des fonctions psychomotrices et du vécu corporel.',
      schema: {
        fields: [
          {
            id: 'motif_demande',
            label: 'Motif de la consultation psychomotrice',
            type: 'textarea',
            required: true,
            placeholder: 'Difficultés de coordination, agitation motrice, anxiété corporelle, graphisme...',
          },
          {
            id: 'contexte_developpemental',
            label: 'Contexte familial, scolaire ou institutionnel',
            type: 'textarea',
            required: false,
            placeholder: 'Étapes du développement, scolarité, comportement rapporté...',
          },
          {
            id: 'tonus_posture',
            label: 'Tonus et régulation tonico-émotionnelle',
            type: 'textarea',
            required: false,
            placeholder: 'Hyper/hypotonie, syncinésies, relaxation, réactions de prestance...',
          },
          {
            id: 'motricite_globale_fine',
            label: 'Motricité globale, fine et coordinations',
            type: 'textarea',
            required: false,
            placeholder: 'Équilibre statique/dynamique, dissociation, habileté manuelle, graphomotricité...',
          },
          {
            id: 'schema_corporel_spatialite',
            label: 'Schéma corporel, image du corps et organisation spatio-temporelle',
            type: 'textarea',
            required: false,
            placeholder: 'Latéralité, repérage dans l’espace et le temps, conscience corporelle...',
          },
          {
            id: 'objectifs_therapeutiques',
            label: 'Objectifs du projet psychomoteur',
            type: 'textarea',
            required: false,
            placeholder: 'Axes de rééducation, médiations corporelles préconisées...',
          },
        ],
      },
    },
    {
      id: 'psychomotor.session_follow_up_form',
      name: 'Suivi de séance psychomotrice',
      kind: 'follow_up',
      description: 'Trame de suivi des médiations et de l’engagement corporel.',
      schema: {
        fields: [
          {
            id: 'mediations_utilisees',
            label: 'Médiations psychomotrices utilisées',
            type: 'textarea',
            required: true,
            placeholder: 'Parcours moteur, relaxation, jeux de balle, graphisme, rythme...',
          },
          {
            id: 'engagement_relationnel',
            label: 'Engagement corporel et relationnel (1-5)',
            type: 'scale',
            min: 1,
            max: 5,
            step: 1,
            required: false,
          },
          {
            id: 'observations_cliniques',
            label: 'Observations cliniques en séance',
            type: 'textarea',
            required: false,
            placeholder: 'Qualité tonique, régulation des émotions, initiatives corporelles...',
          },
          {
            id: 'evolution_motrice',
            label: 'Évolution constatée et perspectives',
            type: 'textarea',
            required: false,
            placeholder: 'Acquisitions, transferts dans le quotidien...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'goal_progress',
      label: 'Progression des objectifs psychomoteurs',
      valueType: 'numeric',
      unit: '%',
      description: 'Taux indicatif d’atteinte des objectifs de séance.',
    },
    {
      code: 'session_engagement',
      label: 'Engagement et disponibilité en séance',
      valueType: 'numeric',
      unit: '/5',
      description: 'Disponibilité corporelle et relationnelle en séance.',
    },
    {
      code: 'motor_score',
      label: 'Score d’aisance motrice et gestuelle',
      valueType: 'numeric',
      unit: '/10',
      description: 'Indice indicatif de coordination et de fluidité gestuelle.',
    },
  ],
};
