import type { ParamedicalProfessionPack } from './types';

export const SPEECH_THERAPIST_PACK: ParamedicalProfessionPack = {
  profession: 'speech_therapist',
  label: 'Orthophoniste',
  clinicalHeaderTitle: 'Dossier de suivi orthophonique',
  terminology: {
    customerSingular: 'Patient',
    customerPlural: 'Patients',
    appointmentSingular: 'Séance',
    appointmentPlural: 'Séances',
    serviceSingular: 'Séance d’orthophonie',
    servicePlural: 'Séances d’orthophonie',
    assessmentLabel: 'Bilan orthophonique initial',
    followUpLabel: 'Séance de rééducation',
    clinicalRecordHeading: 'Dossier orthophonique',
  },
  appointmentTypePresets: [
    {
      id: 'speech.initial_assessment',
      name: 'Bilan orthophonique initial',
      description: 'Bilan complet des fonctions de communication, langage oral/écrit ou déglutition.',
      durationMinutes: 60,
      bufferBeforeMinutes: 10,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
    {
      id: 'speech.follow_up',
      name: 'Séance de rééducation orthophonique',
      description: 'Séance de remédiation et d’entraînement ciblé des compétences de communication.',
      durationMinutes: 30,
      bufferBeforeMinutes: 0,
      bufferAfterMinutes: 5,
      slotStepMinutes: 15,
    },
  ],
  formTemplatePresets: [
    {
      id: 'speech.initial_assessment_form',
      name: 'Bilan initial orthophonique',
      kind: 'assessment',
      description: 'Trame d’évaluation initiale : anamnèse, domaines observés et objectifs de rééducation.',
      schema: {
        fields: [
          {
            id: 'motif_bilan',
            label: 'Motif de la demande de bilan',
            type: 'textarea',
            required: true,
            placeholder: 'Difficultés rapportées (scolaires, articulation, voix, déglutition)...',
          },
          {
            id: 'contexte_developpemental',
            label: 'Contexte et développement',
            type: 'textarea',
            required: false,
            placeholder: 'Antécédents ORL, scolarité, bilinguisme, environnement...',
          },
          {
            id: 'domaines_observes',
            label: 'Domaines explorés lors du bilan',
            type: 'multiple_choice',
            required: true,
            options: [
              { value: 'langage_oral', label: 'Langage oral / Articulation' },
              { value: 'langage_ecrit', label: 'Langage écrit (lecture / orthographe)' },
              { value: 'deglutition_oralite', label: 'Déglutition / Fonctions oro-myo-faciales' },
              { value: 'voix_begaiement', label: 'Voix / Fluence et bégaiement' },
              { value: 'fonctions_cognitives', label: 'Cognition mathématique / Mémoire de travail' },
              { value: 'neurologie', label: 'Pathologies neurologiques / Aphasie' },
            ],
          },
          {
            id: 'objectifs_reeducation',
            label: 'Objectifs prioritaires de rééducation',
            type: 'textarea',
            required: false,
            placeholder: 'Objectifs à court et moyen terme partagés avec le patient ou la famille...',
          },
          {
            id: 'observations_cliniques',
            label: 'Observations et axes de travail retenus',
            type: 'textarea',
            required: false,
            placeholder: 'Fréquence proposée, matériel, préconisations...',
          },
        ],
      },
    },
    {
      id: 'speech.goals_follow_up_form',
      name: 'Suivi des objectifs orthophoniques',
      kind: 'follow_up',
      description: 'Trame de suivi des séances et progression des objectifs.',
      schema: {
        fields: [
          {
            id: 'activites_realisees',
            label: 'Activités et exercices réalisés en séance',
            type: 'textarea',
            required: true,
            placeholder: 'Support utilisé, entraînement phonologique, exercices de fluence...',
          },
          {
            id: 'progression_observee',
            label: 'Progression et réussites observées',
            type: 'textarea',
            required: false,
            placeholder: 'Niveau de transfert, autonomie dans les tâches...',
          },
          {
            id: 'engagement_patient',
            label: 'Implication et attention du patient (1-5)',
            type: 'scale',
            min: 1,
            max: 5,
            step: 1,
            required: false,
          },
          {
            id: 'prochaines_etapes',
            label: 'Notes et préparation de la prochaine séance',
            type: 'textarea',
            required: false,
            placeholder: 'Pistes à approfondir, consignes pour la maison...',
          },
        ],
      },
    },
  ],
  measurementPresets: [
    {
      code: 'goal_progress',
      label: 'Progression des objectifs',
      valueType: 'numeric',
      unit: '%',
      description: 'Taux indicatif d’atteinte des objectifs de travail.',
    },
    {
      code: 'session_engagement',
      label: 'Niveau d’engagement en séance',
      valueType: 'numeric',
      unit: '/5',
      description: 'Évaluation indicative de la participation active.',
    },
    {
      code: 'phoneme_accuracy',
      label: 'Précision articulatoire / phonologique',
      valueType: 'numeric',
      unit: '%',
      description: 'Pourcentage de réussite sur les séries cibles.',
    },
  ],
};
